# Generated by Django 4.0.5 on 2022-06-18 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('cost', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sports_accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('cat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sports_accessories.category')),
            ],
        ),
    ]
